### ISSUE TITLE
Code injection via ads is not mentioned in threats

### ISSUE THREAD

**Issue by alvestrand** [WICG/raw-sockets#11]
The most common method of having a page run Javascript the page doesn't know about is to insert it in an ad (see, for instance, Geoff Huston's IPv6 penetration measurements, which are mainly done via Google ads).

The security implications of this form of code injection needs to be explored.

**Comment by ewilligers** [comment]
Use of the API by third party iframes will be (by default) blocked by Permissions Policy: 

> A permissions policy will control access, preventing third party use by default.

https://github.com/WICG/raw-sockets/pull/8/files also has

> User agents should reject connection attempts when [Content Security Policy](https://w3c.github.io/webappsec-csp/) allows the `unsafe-eval` source expression.
