### ISSUE TITLE
Huge P2P Potential

### ISSUE THREAD

**Issue by TensorTom** [WICG/raw-sockets#30]
I just want to mention how much I'm in favour of this API. Current in-browser p2p is a lame duck because of NAT. In order to bootstrap a mesh, we have to rely on centralized websockets servers for signaling. The introduction of raw sockets opens up the possibility for in-browser servers, which I believe to be essential for the next generation of web. Of course we do want a permission ask when user visits.

**Comment by phoglenix** [comment]
Thanks for the interest!
Note that we are initially looking at outgoing connections only, not listening for connections, and making a single connection at a time. So P2P/servers wouldn't be supported yet. This limits the scope and security discussions so we can hopefully make incremental progress.
I'm going to close this, but it's good to know people are interested in using the API.

**Comment by TensorTom** [comment]
> Thanks for the interest!
> Note that we are initially looking at outgoing connections only, not listening for connections, and making a single connection at a time. So P2P/servers wouldn't be supported yet. This limits the scope and security discussions so we can hopefully make incremental progress.
> I'm going to close this, but it's good to know people are interested in using the API.

Thanks for the kind reply. However, an inability to listen for connections (Open a new port) is somewhat immaterial to the issue. If we have UDP sockets, we can perform NAT hole punching without needing to open a new port since WebRTC already opens one.
